# docker-compose -f docker-compose.dev.yml up --build

services:
  dev-nginx:
    image: nginx
    ports:
      - 8025:80
      - 44325:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  dev-web:
    build:
      context: ./../reelix.frontend/reelix.frontend.website/
      dockerfile: ../../reelix.docker/dockerfiles/Dockerfile.web
    working_dir: /app
    volumes:
      - ./../reelix.frontend/reelix.frontend.website/:/app
      - /app/node_modules
    ports:
      - 44141:44141 # Web port
    restart: unless-stopped

  dev-api:
    build:
      context: ./../reelix.api/
      dockerfile: ../reelix.docker/dockerfiles/Dockerfile.api
    working_dir: /app
    volumes:
      - ./../reelix.api/ReelixApi:/app
      - /app/bin
      - /app/obj
    ports:
      - 48454:48454 # API port
      - 5678:5678 # Debug port
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
    restart: unless-stopped

  dev-mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: reelix
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - 3306:3306 # MariaDB port
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  dev-neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - 7474:7474 # Neo4j HTTP port
      - 7687:7687 # Neo4j Bolt port
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  mariadb_data:
  neo4j_data:
